name: Build library

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
#     - name: Install dependencies
#       run: |
#         brew install openssl
#         brew install autoconf
#         brew install automake
#         brew install libtool
#         brew install cmake
#     - name: build
#       run: ./build.sh
    - name: Maven deploy
      run: mvn clean deploy
    - name: Gradle plugin deploy
      run: cd plugins/gradle && ./gradlew uploadArchives
